name: Manual Hello World

on:
  workflow_dispatch:
  push:
    on_branches:
    - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, world!"